# Build and deploy OpenMaps Vue 3 to S3 for development preview
# Deploys to openmaps-dev.phila.gov

name: dev Push to S3

on:
  push:
    branches:
      - vue3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"

      - name: Configure FontAwesome registry
        run: |
          echo "@fortawesome:registry=https://npm.fontawesome.com/" >> .npmrc
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FA_AUTH_TOKEN }}" >> .npmrc

      - name: pnpm install
        run: pnpm install

      - name: Build
        run: pnpm build
        env:
          VITE_GATEKEEPER_KEY: ${{ secrets.VITE_GATEKEEPER_KEY }}
          VITE_CYCLOMEDIA_API_KEY: ${{ secrets.VITE_CYCLOMEDIA_API_KEY }}
          VITE_CYCLOMEDIA_PASSWORD: ${{ secrets.VITE_CYCLOMEDIA_PASSWORD }}
          VITE_CYCLOMEDIA_USERNAME: ${{ secrets.VITE_CYCLOMEDIA_USERNAME }}
          VITE_PICTOMETRY_CLIENT_ID: ${{ secrets.VITE_PICTOMETRY_CLIENT_ID }}
          VITE_PICTOMETRY_CLIENT_SECRET: ${{ secrets.VITE_PICTOMETRY_CLIENT_SECRET }}

      - name: Deploy to openmaps-dev.phila.gov
        env:
          AWS_DEFAULT_REGION: "us-east-1"
          AWS_S3_BUCKET: openmaps-dev.phila.gov
          AWS_CLOUDFRONT_DISTRIBUTION: E3T7BKDV4NKW92
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync dist s3://$AWS_S3_BUCKET --region us-east-1 --delete
          aws s3 cp s3://$AWS_S3_BUCKET s3://$AWS_S3_BUCKET --recursive --exclude "*" --include "*.html" --metadata-directive REPLACE --acl public-read --cache-control max-age=0,no-cache,no-store,must-revalidate,proxy-revalidate,public --expires "0" --content-type "text/html; charset=utf-8"
          aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION --paths "/*"
